# Tondi Scan Development Environment Configuration
# 开发环境配置文件

[server]
host_url = "127.0.0.1:3000"
grpc_url = "grpc://8.210.45.192:16610"
database_url = "postgres://postgres:postgres@127.0.0.1/postgres"
log_level = "debug"
environment = "development"

[server.cors]
# 开发环境允许所有来源
allowed_origins = []
allowed_methods = []
allowed_headers = []
max_age = 3600

[server.security]
rate_limit = 1000  # 开发环境放宽限制
max_body_size = 10485760  # 10MB

[server.events]
enabled_events = [
    "block-added",
    "utxos-changed",
    "virtual-chain-changed",
    "new-block-template",
    "finality-conflict",
    "finality-conflict-resolved"
]

event_strategy = "real-time"

[server.events.batch]
batch_size = 50
batch_timeout_ms = 50

[server.events.priority]
high_priority = ["block-added", "utxos-changed"]
medium_priority = ["virtual-chain-changed"]
low_priority = ["new-block-template"]

buffer_size = 500
enable_deduplication = true

[server.wrpc]
enabled = true
protocol = "ws"
host = "8.210.45.192"
port = 0
network = "devnet"
encoding = "borsh"

[client]
# WASM Client Configuration for Development
default_network = "devnet"
default_encoding = "borsh"
default_host = "8.210.45.192"
default_protocol = "ws"  # 开发环境使用 ws 而不是 wss

connection_timeout_ms = 5000  # 开发环境缩短超时
ping_interval_ms = 15000
auto_reconnect = true
max_reconnect_attempts = 10
reconnect_delay_ms = 500

default_events = [
    "block-added",
    "utxos-changed", 
    "virtual-chain-changed",
    "new-block-template"
]

log_level = "debug"
enable_console_log = true

[database]
url = "postgres://postgres:postgres@127.0.0.1/postgres"
max_connections = 5
min_connections = 1
connection_timeout = 10
idle_timeout = 60

[logging]
level = "debug"
format = "text"  # 开发环境使用文本格式，便于调试
output = "stdout"
file_path = "logs/tondi-scan-dev.log"

[monitoring]
enabled = false  # 开发环境关闭监控
metrics_port = 9091
health_check_interval = 60
prometheus_endpoint = "/metrics"

# 开发环境特定配置
[development]
# 热重载设置
hot_reload = true
watch_files = true
debug_mode = true

# 开发工具设置
enable_swagger = true
enable_graphql_playground = true
enable_debug_endpoints = true

# 模拟数据设置
mock_data = true
fake_blocks = true
simulate_network_delay = true
