[env]
PROTOWIRE_DIR = { value = "protowire", relative = true }
PROTO_GEN_DIR = { value = "proto_gen", relative = true }

# MIMALLOC_SHOW_STATS = '1'
# MIMALLOC_VERBOSE    = '1'
RUST_LOG = 'trace,h2=info'

# [target.x86_64-unknown-linux-gnu]
# linker    = "clang"
# rustflags = ["-Clink-arg=-Wl,--no-rosegment", "-Clink-arg=-fuse-ld=lld"]
